# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  db : 'mongodb://$(db_username):$(db_password)@$(db_url):$(db_port)'
  dockerRegistryServiceConnection: '64c83f37-a048-4941-a52c-8e76e8ce5996'
  imageRepository: 'peakblockbackend'
  containerRegistry: 'cohub.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'cohube837-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: BuildBackend
  displayName: Build backend stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build the docker image 
      inputs:
        command: 'build'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)
        arguments: '--build-arg db_var=$(db)'
        buildContext: '$(Build.SourcesDirectory)/backend'
    - task: Docker@2
      displayName: Push the image to container registry
      inputs:
        command: 'push'
        repository: $(imageRepository)
        dockerfile: $(backenddockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection) 
        
    - upload: backend/manifests
      artifact: backend_manifests

- stage: DeployBackend
  displayName: Deploy backend stage
  dependsOn: BuildBackend

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'taguacilPeakBlock.ingress-basic'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/backend_manifests/deployment.yml
                $(Pipeline.Workspace)/backend_manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)