apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: peakblockbackend 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: peakblockbackend 
    spec:
      containers:
        - name: peakblockbackend 
          image: cohub.azurecr.io/peakblockbackend
          ports:
          - containerPort: 3000